### ISSUE TITLE
Add similar functional test to 15Q-16Q

### ISSUE THREAD

**Issue by dhermes** [dhermes/bezier#105]
```python
nodes1 = np.asfortranarray([
    [1.0, 1.5, 2.0, 1.25, 1.75, 1.5],
    [0.0, 1.0, 0.0, 0.75, 0.75, 1.5],
])
nodes2 = np.asfortranarray([
    [3.0, 1.5, 0.0,  2.25,  0.75,  1.5],
    [0.0, 1.0, 0.0, -1.5 , -1.5, -3.0],
])
```

![figure_2](https://user-images.githubusercontent.com/520669/35956706-3ec75f76-0c4c-11e8-9743-128ff769fbda.png)

**Comment by dhermes** [comment]
This ([currently][1]) will cause a failure:

```python
>>> import numpy as np
>>> from bezier._intersection_helpers import Intersection
>>> from bezier._surface_helpers import classify_tangent_intersection
>>> nodes1 = np.asfortranarray([
...     [1.0, 1.5, 2.0],
...     [0.0, 1.0, 0.0],
... ])
>>> tangent1 = np.asfortranarray([
...     [1.0],
...     [0.0],
... ])
>>> nodes2 = np.asfortranarray([
...     [3.0, 1.5, 0.0],
...     [0.0, 1.0, 0.0],
... ])
>>> tangent2 = np.asfortranarray([
...     [-3.0],
...     [ 0.0],
... ])
>>> intersection = Intersection(0, 0.5, 0, 0.5)
>>> classify_tangent_intersection(
...     intersection, nodes1, tangent1, nodes2, tangent2)
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File ".../bezier/_surface_helpers.py", line 1051, in classify_tangent_intersection
    raise NotImplementedError(_BAD_TANGENT)
NotImplementedError: Curves moving in opposite direction but define overlapping arcs.
```

whereas the 15Q-16Q example fails on the [other branch][2].

[1]: https://github.com/dhermes/bezier/blob/d8ebe56bc4c2443886ae3f63a165c0b7dff4b69f/src/bezier/_surface_helpers.py#L1051
[2]: https://github.com/dhermes/bezier/blob/d8ebe56bc4c2443886ae3f63a165c0b7dff4b69f/src/bezier/_surface_helpers.py#L1043

**Comment by dhermes** [comment]
I had forgotten a similar example [exists][1] in the `classify-intersection5` doctest:

```python
nodes1 = np.asfortranarray([
    [1.0, 1.5, 2.0, 1.25  , 1.75  , 1.5  ],
    [0.0, 1.0, 0.0, 0.9375, 0.9375, 1.875],
])
surface1 = bezier.Surface.from_nodes(nodes1)
nodes2 = np.asfortranarray([
    [3.0, 1.5, 0.0,  2.25,  0.75,  1.5],
    [0.0, 1.0, 0.0, -2.0 , -2.0 , -4.0],
])
surface2 = bezier.Surface.from_nodes(nodes2)
```

![figure_1](https://user-images.githubusercontent.com/520669/36162162-8171a870-109a-11e8-9c2b-de62f3a6dff7.png)

[1]: https://github.com/dhermes/bezier/blob/8625eedefdb5fdb36c6bbb5c6eba7338e244dcc4/docs/make_images.py#L832-L839

**Comment by dhermes** [comment]
In order to avoid adding two new surfaces to `surfaces.json`, I made one that re-uses [10Q][1]:

```python
nodes1 = np.asfortranarray([  # 10Q
    [1.0, 0.5 , 0.0,  0.75 ,  0.25 ,  0.5 ],
    [0.0, 0.25, 0.0, -0.375, -0.375, -0.75]
])
surface1 = bezier.Surface.from_nodes(nodes1)
nodes2 = np.asfortranarray([
    [0.25, 0.5 , 0.75, 0.375, 0.625, 0.5],
    [0.0 , 0.25, 0.0 , 0.25 , 0.25 , 0.5],
])
surface2 = bezier.Surface.from_nodes(nodes2)
```

![figure_1](https://user-images.githubusercontent.com/520669/36163084-249a95c8-109d-11e8-8936-1df8710bf2ec.png)

[1]: https://github.com/dhermes/bezier/blob/8625eedefdb5fdb36c6bbb5c6eba7338e244dcc4/tests/functional/surfaces.json#L134
