### ISSUE TITLE
Using `Surface.intersect()` for `classify_intersection5.png`

### ISSUE THREAD

**Issue by dhermes** [dhermes/bezier#106]
Currently, the surface of intersection is manually [specified][1] and that is required because it fails with

```python
Traceback (most recent call last):
  File ".../docs/make_images.py", line 850, in classify_intersection5
    intersection, = surface1.intersect(surface2)
  File ".../bezier/surface.py", line 947, in intersect
    self._nodes, self._degree, other._nodes, other._degree, _verify)
  File "src/bezier/_speedup.pyx", line 1081, in bezier._speedup.surface_intersections
    raise NotImplementedError('Line segments parallel.')
```

[1]: https://github.com/dhermes/bezier/blob/1eb6d850a60cacb2eebf3fe567f908d39c513da6/docs/make_images.py#L849-L866

**Comment by dhermes** [comment]
This was filed due to https://github.com/dhermes/bezier/commit/c7fe4b78ee0a3e31d68afd7100d16d06300325f3.

It turns out this isn't so cut-and-dry since those curved polygons are intentionally "split" at the point of tangency.
