### ISSUE TITLE
Wrong length for "degree-zero" curves

### ISSUE THREAD

**Issue by anntzer** [dhermes/bezier#148]
I don't know if you want to "support" degree-zero "curves" (i.e., a single point), but right now they are constructible and for example `evaluate()` returns the correct point.

However, `length` appears to return some uninitialized memory value for such "curves":
```python
In [7]: bezier.Curve.from_nodes(np.array([[0.], [0.]])).length                                                      
Out[7]: 0.0

In [8]: bezier.Curve.from_nodes(np.array([[0.], [0.]])).length                                                      
Out[8]: 0.0

In [9]: bezier.Curve.from_nodes(np.array([[0.], [0.]])).length                                                      
Out[9]: 0.0

In [10]: bezier.Curve.from_nodes(np.array([[0.], [0.]])).length                                                     
Out[10]: 2.8281143278872597e+303

In [11]: bezier.Curve.from_nodes(np.array([[0.], [0.]])).length                                                     
Out[11]: 3.8621377243993127e+228

In [12]: bezier.Curve.from_nodes(np.array([[0.], [0.]])).length                                                     
Out[12]: 1.0043102985027076e+289

In [13]: bezier.Curve.from_nodes(np.array([[0.], [0.]])).length                                                     
Out[13]: 0.0

In [14]: bezier.Curve.from_nodes(np.array([[0.], [0.]])).length                                                     
Out[14]: 0.0

In [15]: bezier.Curve.from_nodes(np.array([[0.], [0.]])).length                                                     
Out[15]: 0.0
```

**Comment by dhermes** [comment]
Thanks for bringing this bug to my attention. The Python version actually fails (but the Fortran version is the broken one). Installing via:

```
python3.7 -m virtualenv venv
BEZIER_NO_EXTENSIONS=True venv/bin/python -m pip install bezier==0.9.0 --no-binary=bezier
venv/bin/python -m pip install ipython scipy
```

we can see:

```python
In [1]: %xmode plain
Exception reporting mode: Plain

In [2]: import numpy as np

In [3]: import bezier

In [4]: bezier._HAS_SPEEDUP
Out[4]: False

In [5]: bezier.Curve.from_nodes(np.array([[0.], [0.]])).length
Traceback (most recent call last):
  File "<ipython-input-5-cc14e749cd5a>", line 1, in <module>
    bezier.Curve.from_nodes(np.array([[0.], [0.]])).length
  File ".../venv/lib/python3.7/site-packages/bezier/curve.py", line 146, in length
    return _curve_helpers.compute_length(self._nodes)
  File ".../venv/lib/python3.7/site-packages/bezier/_curve_helpers.py", line 342, in _compute_length
    length, _ = _scipy_int.quad(size_func, 0.0, 1.0)
  File ".../venv/lib/python3.7/site-packages/scipy/integrate/quadpack.py", line 341, in quad
    points)
  File ".../venv/lib/python3.7/site-packages/scipy/integrate/quadpack.py", line 448, in _quad
    return _quadpack._qagse(func,a,b,args,full_output,epsabs,epsrel,limit)
  File ".../venv/lib/python3.7/site-packages/bezier/_curve_helpers.py", line 294, in vec_size
    result_vec = evaluate_multi(nodes, np.asfortranarray([s_val]))
  File ".../venv/lib/python3.7/site-packages/bezier/_curve_helpers.py", line 219, in _evaluate_multi
    return evaluate_multi_barycentric(nodes, one_less, s_vals)
  File ".../venv/lib/python3.7/site-packages/bezier/_curve_helpers.py", line 264, in _evaluate_multi_barycentric
    result += lambda1 * nodes[:, [0]]
IndexError: index 0 is out of bounds for axis 1 with size 0
```

**Comment by dhermes** [comment]
The [culprit][1] checks for degree 1 and assumes everything else is greater. This could be fixed like so:

```fortran
    if (num_nodes == 0) then
       error_val = -1
       return
    else if (num_nodes == 1) then
       length = 0.0
       error_val = 0
       return
    else if (num_nodes == 2) then
       length = norm2(first_deriv)
       error_val = 0
       return
    end if
```

and the Python [equivalent][2] fixed with:

```python
    if num_nodes == 0:
        raise _helpers.UnsupportedDegree(-1)  # May need to modify this class a bit
    elif num_nodes == 1:
        return 0.0
    elif num_nodes == 2:
        # NOTE: We convert to 1D to make sure NumPy uses vector norm.
        return np.linalg.norm(first_deriv[:, 0], ord=2)
```

[1]: https://github.com/dhermes/bezier/blob/4f941f82637a8e70a5b159a9203132192e23406b/src/bezier/curve.f90#L820-L824
[2]: https://github.com/dhermes/bezier/blob/4f941f82637a8e70a5b159a9203132192e23406b/src/bezier/_curve_helpers.py#L334-L336
