### ISSUE TITLE
Surface-surface intersection fails on "almost" parallel lines

### ISSUE THREAD

**Issue by dhermes** [dhermes/bezier#18]
```python
>>> import numpy as np
>>> nodes1 = np.asfortranarray([
...     [1.625 , 1.1875 ],
...     [1.5   , 1.03125],
...     [1.375 , 0.875  ],
...     [1.6875, 1.0    ],
...     [1.5625, 0.84375],
...     [1.75  , 0.8125 ],
... ])
>>> nodes2 = np.asfortranarray([
...     [1.25     , 0.75     ],
...     [1.34375  , 0.78125  ],
...     [1.4375   , 0.8125   ],
...     [1.375    , 0.875    ],
...     [1.4609375, 0.9140625],
...     [1.484375 , 1.015625 ],
... ])
>>> import bezier
>>> S1 = bezier.Surface(nodes1, degree=2, _copy=False)
>>> S2 = bezier.Surface(nodes2, degree=2, _copy=False)
>>> import seaborn
>>> ax = S1.plot(256)
>>> _ = S2.plot(256, ax=ax)
>>> _ = ax.axis('scaled')
>>> ax.figure.show()
>>> S1.intersect(S2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "bezier/surface.py", line 1144, in intersect
    edge_pairs)
  File "bezier/_intersection_helpers.py", line 1437, in all_intersections
    raise NotImplementedError(msg)
NotImplementedError: The number of candidate intersections is too high.
17 accepted pairs gives 68 candidate pairs.
```

![figure_1](https://cloud.githubusercontent.com/assets/520669/22129085/d8ff08c8-de58-11e6-83d0-3937d22fa9bd.png)

This actually comes from a single edge-pair (I originally assumed the issue was that the bound of 16 for two curves was overly restrictive for multiple curves, relaxing to 20 allows this to pass BTW)

```python
>>> for i, edge1 in enumerate(S1.edges):
...     for j, edge2 in enumerate(S2.edges):
...         try:
...             I = edge1.intersect(edge2)
...             print('{}, {} success'.format(i, j))
...         except NotImplementedError:
...             print('{}, {} failure'.format(i, j))
... 
0, 0 success
0, 1 success
0, 2 failure
1, 0 success
1, 1 success
1, 2 success
2, 0 success
2, 1 success
2, 2 success
```

So

```python
>>> import numpy as np
>>> nodes1 = np.asfortranarray([
...     [1.625 , 1.1875 ],
...     [1.5   , 1.03125],
...     [1.375 , 0.875  ],
... ])
>>> nodes2 = np.asfortranarray([
...     [1.484375, 1.015625],
...     [1.375   , 0.875   ],
...     [1.25    , 0.75    ],
... ])
>>> import bezier
>>> C1 = bezier.Curve(nodes1, degree=2, _copy=False)
>>> C2 = bezier.Curve(nodes2, degree=2, _copy=False)
>>> import seaborn
>>> ax = C1.plot(256)
>>> _ = C2.plot(256, ax=ax)
>>> _ = ax.axis('scaled')
>>> ax.figure.show()
>>> C1.intersect(C2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "bezier/curve.py", line 583, in intersect
    intersections = _intersection_helpers.all_intersections(candidates)
  File "bezier/_intersection_helpers.py", line 1437, in all_intersections
    raise NotImplementedError(msg)
NotImplementedError: The number of candidate intersections is too high.
17 accepted pairs gives 68 candidate pairs.
```

and the crazy thing is, they never intersect!

![figure_1](https://cloud.githubusercontent.com/assets/520669/22129275/cf96eb7e-de59-11e6-9d28-4c63aaaf90eb.png)

Via [implicitization][1], this is straightforward to dismiss:

```
Computed f(t) = f1(x2(t), y2(t)) =
    (-0.0009765625) * t^0 + (0.001953125) * t^1 + (-0.0087890625) * t^2
======
Resultant(f, f') = -5.78476 (computed with L2-normalized ||f|| = 1 on [0, 1])
Roots:
```

This `f(t)` is just `9 t^2 - 2 t + 1` divided by `-1024`. The unscaled version has discriminant equal to `(-2)^2 - 4(9)(1) = -32`, so it has no real roots.

```python
>>> from bezier._intersection_helpers import IntersectionStrategy
>>> I, = S1.intersect(S2, strategy=IntersectionStrategy.algebraic)
>>> I
<CurvedPolygon (num_sides=3)>
>>>
>>> ax = S1.plot(256)
>>> _ = S2.plot(256, ax=ax)
>>> _ = I.plot(256, ax=ax)
>>> _ = ax.axis('scaled')
>>> ax.figure.show()
```

![figure_1](https://cloud.githubusercontent.com/assets/520669/26339484/1effa892-3f3d-11e7-9108-6d805a8c37c3.png)

[1]: https://gist.github.com/dhermes/29f3c98c87d91bc0f41349915142e3d7/fa17c7eed24e86ad41116a84e8114e0d7b80627f#file-output-txt-L239-L253

----

```
$ git log -1 --pretty=%H
09550abcf0efeb239b17f9871ccac93fcd1bcd4a
$ # UPDATED: Still b0rken
$ git log -1 --pretty=%H
7a86d904b2e9b48decbd5d6b3fd2340d492b3947
```

**Comment by dhermes** [comment]
This was fixed by https://github.com/dhermes/bezier/commit/80248276bb32be2bc2851cc81eff74599a41754f and related commits. As of 4b773f340145aceaf7f8764411e13aadd7eb83b8:

```python
>>> import numpy as np
>>> nodes1 = np.array([
...     [1.625 , 1.1875 ],
...     [1.5   , 1.03125],
...     [1.375 , 0.875  ],
...     [1.6875, 1.0    ],
...     [1.5625, 0.84375],
...     [1.75  , 0.8125 ],
... ], order='C').T
>>> nodes2 = np.array([
...     [1.25     , 0.75     ],
...     [1.34375  , 0.78125  ],
...     [1.4375   , 0.8125   ],
...     [1.375    , 0.875    ],
...     [1.4609375, 0.9140625],
...     [1.484375 , 1.015625 ],
... ], order='C').T
>>> import bezier
>>> S1 = bezier.Surface(nodes1, degree=2, _copy=False)
>>> S2 = bezier.Surface(nodes2, degree=2, _copy=False)
>>> I, = S1.intersect(S2)
>>> I
<CurvedPolygon (num_sides=3)>
>>>
>>> import seaborn
>>> seaborn.set()
>>> ax = S1.plot(256)
>>> _ = S2.plot(256, ax=ax)
>>> _ = I.plot(256, ax=ax)
>>> _ = ax.axis('scaled')
>>> ax.figure.show()
```

![figure_2](https://user-images.githubusercontent.com/520669/36175696-34adfee6-10c5-11e8-9c1b-baa97c176f37.png)
