### ISSUE TITLE
Syntax Error when importing Bezier

### ISSUE THREAD

**Issue by ankurjay** [dhermes/bezier#285]
When importing Bezier, I get this error:

```
Traceback (most recent call last):
  File "sim.py", line 3, in <module>
    import bezier
  File "/home/tjmax/.local/opt/may/pyenv/versions/3.5.10/lib/python3.5/site-packages/bezier/__init__.py", line 37, in <module>
    from bezier._legacy import Surface
  File "/home/tjmax/.local/opt/may/pyenv/versions/3.5.10/lib/python3.5/site-packages/bezier/_legacy.py", line 17, in <module>
    from bezier import triangle
  File "/home/tjmax/.local/opt/may/pyenv/versions/3.5.10/lib/python3.5/site-packages/bezier/triangle.py", line 270
    f"A degree {self._degree} triangle should have "
                                                   ^
SyntaxError: invalid syntax
```

My python3 version is 3.5.10.

**Comment by dhermes** [comment]
@ankurjay Sorry to hear that. I am so happy you stopped by to file an issue though!

Unfortunately, the minimum supported version of the latest release (`2021.2.12`) is 3.7 and the very next release will raise that minimum to 3.8. The syntax you are seeing (f-strings) was added in Python 3.6.

See #278 for recent changes I made to at least make it more obvious if a user is on an unsupported version of Python.

----

I am going to preemptively close this issue out because it seems I've answered your query. Do let me know if you'd like to continue discussion and I'm happy to re-open the ticket.
