### ISSUE TITLE
“python_requires” should be set with “>=3.6”, as Bezier 2021.2.12 is not compatible with all Python versions.

### ISSUE THREAD

**Issue by PyVCEchecker** [dhermes/bezier#291]
Currently, the keyword argument **python_requires** of **setup()** is not set, and thus it is assumed that this distribution is compatible with all Python versions. 
However, I found it is not compatible with **Python<3.6**. My local Python version is 3.5, and I encounter the following error when executing _“pip install bezier”_ 

```
Collecting bezier
  Downloading bezier-2021.2.12.tar.gz (313 kB)
     |████████████████████████████████| 313 kB 522 kB/s 
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-huyv7pdh/bezier/setup.py'"'"'; __file__='"'"'/tmp/pip-install-huyv7pdh/bezier/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-zjnnkq8b
         cwd: /tmp/pip-install-huyv7pdh/bezier/
    Complete output (6 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-huyv7pdh/bezier/setup.py", line 177
        dll_name = f"bezier-{short_hash}.dll"
                                            ^
    SyntaxError: invalid syntax
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

I found that **setup.py** used the syntax feature __f-string__. The feature is only compatible with Python 3.6 and above, leading to installation failure of bezier in Python3.5. 

Way to fix:
modify **setup()** in **setup.py,** add **python_requires** keyword argument:
```python
setup(…
     python_requires='>=3.6',
     …)
```
Thanks for your attention.
Best regrads,
PyVCEchecker

**Comment by dhermes** [comment]
Thanks for calling it out!
