### ISSUE TITLE
Fallback to algebraic when geometric fails?

### ISSUE THREAD

**Issue by dhermes** [dhermes/bezier#32]
Consider quadratic curves given by the following points:

```python
>>> import numpy as np
>>> 
>>> F = float.fromhex
>>> 
>>> nodes1 = np.asfortranarray([
...     [F('0x1.002f11833164ap-1'), F('-0x1.32718972d77a1p-1')],
...     [F('0x1.c516e980c0ce0p-2'), F('-0x1.5e002a95d165ep-1')],
...     [F('0x1.89092ee6e6df4p-2'), F('-0x1.8640e302433dfp-1')],
... ])
>>> nodes2 = np.asfortranarray([
...     [F('0x1.fbb8cfd966f05p-2'), F('-0x1.325bc2f4e012cp-1')],
...     [F('0x1.c6cd0e74ae3ecp-2'), F('-0x1.614b060a21ebap-1')],
...     [F('0x1.8c4a283f3c04dp-2'), F('-0x1.8192083f28f11p-1')],
... ])
>>>
>>>
>>> known_s1 = F('0x1.3c07c30226a3cp-2')
>>> known_t1 = F('0x1.30f6f2bdde113p-2')
>>>
>>> known_s2 = F('0x1.7d5b269eb3fecp-1')
>>> known_t2 = F('0x1.8700df9eac93bp-1')
```

----

Close-ish visual inspection shows two intersections (Bézout gives at most 4):

```python
>>> import matplotlib.pyplot as plt
>>> import seaborn
>>> 
>>> import bezier
>>> 
>>> seaborn.set()
>>> 
>>> curve1 = bezier.Curve.from_nodes(nodes1, _copy=False)
>>> curve2 = bezier.Curve.from_nodes(nodes2, _copy=False)
>>> 
>>> ax = curve1.plot(256)
>>> _ = curve2.plot(256, ax=ax)
>>> _ = ax.axis('scaled')
>>> ax.figure.show()
```

![figure_1](https://user-images.githubusercontent.com/520669/28142506-00295278-6716-11e7-9e4e-18214739a826.png)

----

However, geometric intersection fails due to too many pairs of subdivided curves that have overlapping bounding boxes:

```python
>>> from bezier._intersection_helpers import all_intersections
>>> from bezier._intersection_helpers import IntersectionStrategy
>>> 
>>> candidates = [(curve1, curve2)]
>>> 
>>> intersections_geom = all_intersections(
...     candidates, strategy=IntersectionStrategy.geometric)
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File ".../bezier/_intersection_helpers.py", line 1501, in all_intersections
    return _all_intersections_geometric(candidates)
  File ".../bezier/_intersection_helpers.py", line 1419, in _all_intersections_geometric
    raise NotImplementedError(msg)
NotImplementedError: The number of candidate intersections is too high.
29 accepted pairs gives 116 candidate pairs.
```

but algebraic intersection has no problem finding two intersections

```python
>>> intersections_alg = all_intersections(
...     candidates, strategy=IntersectionStrategy.algebraic)
>>> len(intersections_alg)
2
>>> (intersections_alg[0].s, intersections_alg[0].t)
(0.30862335873247104, 0.29781703266006965)
>>> (intersections_alg[0].s - known_s1) / np.spacing(known_s1)
-398.0
>>> (intersections_alg[0].t - known_t1) / np.spacing(known_t1)
-417.0
>>>
>>> (intersections_alg[1].s, intersections_alg[1].t)
(0.74483605086606985, 0.76367853938999475)
>>> (intersections_alg[1].s - known_s2) / np.spacing(known_s2)
20.0
>>> (intersections_alg[1].t - known_t2) / np.spacing(known_t2)
23.0
```

----

```
$ git log -1 --pretty=%H
fb863038bc6b3effaf8a401e51e69b18bbf4b0ae
```

**Comment by dhermes** [comment]
It's worth noting that after https://github.com/dhermes/bezier/commit/80248276bb32be2bc2851cc81eff74599a41754f, the above example works just fine in both geometric and algebraic strategies:

```python
>>> nodes1 = np.array([
...     [F('0x1.002f11833164ap-1'), F('-0x1.32718972d77a1p-1')],
...     [F('0x1.c516e980c0ce0p-2'), F('-0x1.5e002a95d165ep-1')],
...     [F('0x1.89092ee6e6df4p-2'), F('-0x1.8640e302433dfp-1')],
... ], order='C').T
>>> nodes2 = np.array([
...     [F('0x1.fbb8cfd966f05p-2'), F('-0x1.325bc2f4e012cp-1')],
...     [F('0x1.c6cd0e74ae3ecp-2'), F('-0x1.614b060a21ebap-1')],
...     [F('0x1.8c4a283f3c04dp-2'), F('-0x1.8192083f28f11p-1')],
... ], order='C').T
>>>
>>> from bezier.curve import IntersectionStrategy
>>> curve1 = bezier.Curve.from_nodes(nodes1)
>>> curve2 = bezier.Curve.from_nodes(nodes2)
>>>
>>> intersection_geom = curve1.intersect(curve2, strategy=IntersectionStrategy.GEOMETRIC)
>>> intersection_geom
array([[0.30862336, 0.74483605],
       [0.29781703, 0.76367854]])
>>> intersection_alg = curve1.intersect(curve2, strategy=IntersectionStrategy.ALGEBRAIC)
>>> intersection_alg
array([[0.30862336, 0.74483605],
       [0.29781703, 0.76367854]])
```

and checking the errors we have

```python
>>> KNOWN = np.asfortranarray([
...     [known_s1, known_s2],
...     [known_t1, known_t2],
... ])
>>>
>>> (intersection_geom - KNOWN) / np.spacing(KNOWN)
array([[-155., 3705.],
       [-164., 3961.]])
>>>
>>> (intersection_alg - KNOWN) / np.spacing(KNOWN)
array([[-398.,   20.],
       [-417.,   23.]])
```
