### ISSUE TITLE
Track down non-deterministic `matplotlib` import error.

### ISSUE THREAD

**Issue by dhermes** [dhermes/bezier#82]
Example:

```
...
Document: reference/bezier.surface
----------------------------------

Warning, treated as error:
**********************************************************************
File "reference/bezier.surface.rst", line 123, in surface-constructor (cleanup code)
Failed example:
    import make_images
    make_images.unit_triangle()
    make_images.surface_constructor(surface)
Exception raised:
    Traceback (most recent call last):
      File "${HOME}/.pyenv/versions/3.6.3/lib/python3.6/doctest.py", line 1330, in __run
        compileflags, 1), test.globs)
      File "<doctest surface-constructor (cleanup code)[0]>", line 2, in <module>
        make_images.unit_triangle()
      File ".../bezier/docs/make_images.py", line 1225, in unit_triangle
        ax = surface.plot(256)
      File ".../bezier/.nox/docs_images/lib/python3.6/site-packages/bezier/surface.py", line 782, in plot
        ax = _plot_helpers.new_axis()
      File ".../bezier/.nox/docs_images/lib/python3.6/site-packages/bezier/_plot_helpers.py", line 32, in new_axis
        import matplotlib.pyplot as plt
      File ".../bezier/.nox/docs_images/lib/python3.6/site-packages/matplotlib/pyplot.py", line 2182, in <module>
        colorbar.__doc__ = matplotlib.colorbar.colorbar_doc
    AttributeError: module 'matplotlib' has no attribute 'colorbar'

nox > Command sphinx-build -W -b doctest -d .../bezier/docs/build/doctrees .../bezier/docs .../bezier/docs/build/doctest failed with exit code 1
nox > Session docs_images failed.
```

For some reason it goes away when the second [set of commands][1] are removed in `nox -s docs_images`.

----

```
$ git log -1 --pretty=%H
97c8b4787dc55e6d914f7d9a8570cccc72993647
```

[1]: https://github.com/dhermes/bezier/blob/97c8b4787dc55e6d914f7d9a8570cccc72993647/nox.py#L246-L247

**Comment by dhermes** [comment]
I can finally walk away from this because I fully understand it:

```python
>>> # Which versions?
>>> import matplotlib
>>> matplotlib.__version__
'2.1.0'
>>> import seaborn
>>> seaborn.__version__
'0.8.1'
>>> # Perform **EVERY** matplotlib import that we use
>>> import matplotlib.pyplot as plt
>>> from matplotlib import patches
>>> from matplotlib import path as _path_mod
>>> # Do what the doctests used to do to `sys.modules`
>>> import sys
>>> sys.modules.pop('matplotlib')
<module 'matplotlib' from '/home/dhermes/.pyenv/versions/3.6.3/lib/python3.6/site-packages/matplotlib/__init__.py'>
>>> sys.modules.pop('matplotlib.pyplot')
<module 'matplotlib.pyplot' from '/home/dhermes/.pyenv/versions/3.6.3/lib/python3.6/site-packages/matplotlib/pyplot.py'>
>>> sys.modules.pop('seaborn')
<module 'seaborn' from '/home/dhermes/.pyenv/versions/3.6.3/lib/python3.6/site-packages/seaborn/__init__.py'>
>>> # Now try to re-import somewhere else
>>> import matplotlib.pyplot as plt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dhermes/.pyenv/versions/3.6.3/lib/python3.6/site-packages/matplotlib/pyplot.py", line 2182, in <module>
    colorbar.__doc__ = matplotlib.colorbar.colorbar_doc
AttributeError: module 'matplotlib' has no attribute 'colorbar'
```
